services:
  db:
    image: postgres:15
    container_name: cesizen_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: cesizen_db
    ports:
      - "5432:5432"