// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});

/*
  Résumé du fichier :
  - Sert à configurer Prisma côté backend.
  - Fonctionne en indiquant le schéma, le dossier des migrations et l'URL de base de données.
*/
